### ISSUE TITLE
Any pre-trained model would you share?

### ISSUE THREAD

**Issue by HulkMaker** [lbf4616/Anti-spoofing#2]

**Comment by youthM** [comment]
@lbf4616

**Comment by lbf4616** [comment]
Two SVM classifier model has already shared in [3DMAD](https://github.com/lbf4616/Face-Anti-spoofing/blob/master/Anti-spoofing/3DMAD.txt) & [LBP](https://github.com/lbf4616/Face-Anti-spoofing/blob/master/Anti-spoofing/LBP19.9.xml). 

Thanks

**Comment by lbf4616** [comment]
Yes, I have already share the
